#!/bin/bash

export TEMP=/tmp/secret/.notes/1p22geo-notes-temp-dir
mkdir -p $TEMP
cd $TEMP
gpg --decrypt ~/Documents/misc/notes.tar.gz.gpg >./notes.tar.gz
tar -xzvf ./notes.tar.gz
obsidian
tar -czvf ./notes.tar.gz ./notes
gpg -r Bartosz\ Geodecki --encrypt ./notes.tar.gz
mv ./notes.tar.gz.gpg ~/Documents/misc/notes.tar.gz.gpg
cd /tmp
rm -rf $TEMP
