#!/usr/bin/python3

import os
import random

filelist = []
print("Indexing files...")
for root,_,files in os.walk("."):
    for file in files:
        pt = os.path.join(root, file)
        if pt in filelist:
            continue
        print(pt)
        filelist.append(pt)



while True:
    search = ""
    file = random.choice(filelist)
    try:
        with open("/tmp/shuffle") as f:
            search = f.read()
    except:
        search = ""
    if not search in file:
        continue
    os.system(f"mplayer \"{file}\"")
